### ISSUE TITLE
ActiveEffect5e validation errors:   name: may not be undefined

### ISSUE THREAD

**Issue by wakitcha** [mclemente/fvtt-condition-lab-triggler#25]
**Describe the bug**
I've recently upgraded to Foundry v11.  I switched from CUB to this module for DnD 5E.  Specifically here I am not able to get the death status application to work when an NPC goes to 0 HP.  Instead of the death status being applied and the icon covering the NPC token, I get three sets of errors like this, and the effect is not applied to the token.

Error: ActiveEffect5e validation errors:
  name: may not be undefined
    at DataModelValidationFailure.asError (commons.js:3894:14)
    at ActiveEffect5e.validate (commons.js:7164:61)
    at new DataModel (commons.js:6918:12)
    at new ClientDocumentMixin (foundry.js:13979:7)
    at new ActiveEffect5e (active-effect.mjs:4:16)
    at #preCreateDocumentArray (foundry.js:13535:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:13428:73)
    at ClientDatabaseBackend.create (commons.js:8629:19)
    at async ActiveEffect5e.createDocuments (commons.js:7958:23)
    at async EnhancedConditions.addCondition (enhanced-conditions.js:1238:27)
    at async Triggler._executeTrigger (triggler.js:126:4)
    at async Triggler._processUpdate (triggler.js:344:5)
onError @ foundry.js:753
foundry.js:68326 ActiveEffect5e validation errors:
  name: may not be undefined
fetch @ foundry.js:68326

**To Reproduce**
1) Set an NPC to 0 HP.

**Expected behavior**
The NPC is given the death status, the icon for death is full over the token.

**Environment Info (please complete the following information):**
 - Foundry Version: 11 build 315
 - Game System / Version: dnd 5e 2.4.0
 - Condition Lab Triggler Version:  1.4.8
 - Browser: Chrome
 - OS: Windows 10

**Comment by wakitcha** [comment]
Hi, I've figured this out.  The conditions that existed from CUB and previous Foundry versions were missing ... something.  I reset my conditions to the defaults from this module and I stopped getting these errors.  Things seem to be working well now. 

I added the death auto-status for NPCs as from CUB and it is working.  I did have to add my own Death condition though.
